apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: timingle

resources:
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: timingle-monitoring
