apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: timingle

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: timingle
  app.kubernetes.io/managed-by: kustomize
